### ISSUE TITLE
Could you provide me with a design document for vlan.c or mvrp? thank you very much

### ISSUE THREAD

**Issue by JimmyLuoX** [michael-dev/mvrpd#6]
I have been studying the code related to the MVRP protocol recently, and despite reviewing your project, I still find myself having some difficulties understanding certain parts, particularly the contents of vlan.c.
I was wondering if you might have any documentation or explanatory materials that I could study. If such resources are available, I would be extremely grateful. 
I apologize for any inconvenience and offer my most sincere regards.
Thank you for your time and consideration.

**Comment by JimmyLuoX** [comment]
The project is missing the config.h file.

**Comment by lhoward** [comment]
Use the script in `autoinstall.sh`, then run `configure`, this should generate `config.h`.

**Comment by michael-dev** [comment]
Sorry, there is no extra documentation .

vlan.c implements an data type (sparse list) to store a list of vlan identifiers to be used within mvrpd.
The abstract data type is defined in vlan.h.
